# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

abs1 <- function(a) {
    .Call('_FBCRM_abs1', PACKAGE = 'FBCRM', a)
}

min1 <- function(a, b) {
    .Call('_FBCRM_min1', PACKAGE = 'FBCRM', a, b)
}

max1 <- function(a, b) {
    .Call('_FBCRM_max1', PACKAGE = 'FBCRM', a, b)
}

upper_bound <- function(zeta, a) {
    .Call('_FBCRM_upper_bound', PACKAGE = 'FBCRM', zeta, a)
}

lower_bound <- function(zeta, a) {
    .Call('_FBCRM_lower_bound', PACKAGE = 'FBCRM', zeta, a)
}

GetBoundaries_p <- function(m, p, zeta) {
    .Call('_FBCRM_GetBoundaries_p', PACKAGE = 'FBCRM', m, p, zeta)
}

TruncNormal_p <- function(m, p, c1, zeta) {
    .Call('_FBCRM_TruncNormal_p', PACKAGE = 'FBCRM', m, p, c1, zeta)
}

q_beta <- function(X, a, b) {
    .Call('_FBCRM_q_beta', PACKAGE = 'FBCRM', X, a, b)
}

myFac <- function(x) {
    .Call('_FBCRM_myFac', PACKAGE = 'FBCRM', x)
}

GammaFn <- function(z) {
    .Call('_FBCRM_GammaFn', PACKAGE = 'FBCRM', z)
}

BetaCDF <- function(z, a, b) {
    .Call('_FBCRM_BetaCDF', PACKAGE = 'FBCRM', z, a, b)
}

QBeta <- function(q, a, b) {
    .Call('_FBCRM_QBeta', PACKAGE = 'FBCRM', q, a, b)
}

TruncBeta <- function(m, p, zeta, a, b) {
    .Call('_FBCRM_TruncBeta', PACKAGE = 'FBCRM', m, p, zeta, a, b)
}

samp1 <- function(p) {
    .Call('_FBCRM_samp1', PACKAGE = 'FBCRM', p)
}

VEC <- function(p) {
    .Call('_FBCRM_VEC', PACKAGE = 'FBCRM', p)
}

SampBinom <- function(samp, prob) {
    .Call('_FBCRM_SampBinom', PACKAGE = 'FBCRM', samp, prob)
}

getmin <- function(dose) {
    .Call('_FBCRM_getmin', PACKAGE = 'FBCRM', dose)
}

optdose <- function(dose, mtd) {
    .Call('_FBCRM_optdose', PACKAGE = 'FBCRM', dose, mtd)
}

LFBCRM1 <- function(X, Y, p, alpha) {
    .Call('_FBCRM_LFBCRM1', PACKAGE = 'FBCRM', X, Y, p, alpha)
}

Lbeta1 <- function(p, a, b, zeta) {
    .Call('_FBCRM_Lbeta1', PACKAGE = 'FBCRM', p, a, b, zeta)
}

randbeta <- function(m, s) {
    .Call('_FBCRM_randbeta', PACKAGE = 'FBCRM', m, s)
}

randnorm <- function(mu, sigma) {
    .Call('_FBCRM_randnorm', PACKAGE = 'FBCRM', mu, sigma)
}

non_zero <- function(X) {
    .Call('_FBCRM_non_zero', PACKAGE = 'FBCRM', X)
}

LM <- function(pi, a, b, X, zeta) {
    .Call('_FBCRM_LM', PACKAGE = 'FBCRM', pi, a, b, X, zeta)
}

LCRM <- function(X, Y, p, alpha) {
    .Call('_FBCRM_LCRM', PACKAGE = 'FBCRM', X, Y, p, alpha)
}

LCRM_1D <- function(x, y, p, al) {
    .Call('_FBCRM_LCRM_1D', PACKAGE = 'FBCRM', x, y, p, al)
}

dn <- function(sigma, alpha) {
    .Call('_FBCRM_dn', PACKAGE = 'FBCRM', sigma, alpha)
}

area <- function(X, Y, p, sigma, a, b, n) {
    .Call('_FBCRM_area', PACKAGE = 'FBCRM', X, Y, p, sigma, a, b, n)
}

areap <- function(X, Y, p, sigma, a, b, n) {
    .Call('_FBCRM_areap', PACKAGE = 'FBCRM', X, Y, p, sigma, a, b, n)
}

areap_d1 <- function(X, Y, p, sigma, mtd, a, b, n) {
    .Call('_FBCRM_areap_d1', PACKAGE = 'FBCRM', X, Y, p, sigma, mtd, a, b, n)
}

CRM_MCMC <- function(X, Y, p, sigma, mtd, a, b, n) {
    .Call('_FBCRM_CRM_MCMC', PACKAGE = 'FBCRM', X, Y, p, sigma, mtd, a, b, n)
}

CRM_RUNTRIAL <- function(cohort, samp, ptrue, p, sigma, mtd, M, p_u, a, b, n) {
    .Call('_FBCRM_CRM_RUNTRIAL', PACKAGE = 'FBCRM', cohort, samp, ptrue, p, sigma, mtd, M, p_u, a, b, n)
}

#'@importFrom Rcpp evalCpp
#'@useDynLib FBCRM
FBCRM_MCMC <- function(X, Y, p, p_rho, sigma, mtd, B) {
    .Call('_FBCRM_FBCRM_MCMC', PACKAGE = 'FBCRM', X, Y, p, p_rho, sigma, mtd, B)
}

#'@importFrom Rcpp evalCpp
#'@useDynLib FBCRM
FBCRM_RUNTRIAL <- function(cohort, max_samp, ptrue, p, p_rho, sigma, mtd, p_u, B, M, a, b, n) {
    .Call('_FBCRM_FBCRM_RUNTRIAL', PACKAGE = 'FBCRM', cohort, max_samp, ptrue, p, p_rho, sigma, mtd, p_u, B, M, a, b, n)
}

BMACRM_RUNTRIAL <- function(cohort, samp, ptrue, skel, sigma, mtd, M, p_u, a, b, n) {
    .Call('_FBCRM_BMACRM_RUNTRIAL', PACKAGE = 'FBCRM', cohort, samp, ptrue, skel, sigma, mtd, M, p_u, a, b, n)
}

samp2 <- function(p, k) {
    .Call('_FBCRM_samp2', PACKAGE = 'FBCRM', p, k)
}

TruncNormal <- function(lower, upper, mean, var) {
    .Call('_FBCRM_TruncNormal', PACKAGE = 'FBCRM', lower, upper, mean, var)
}

#'@importFrom Rcpp evalCpp
#'@useDynLib FBCRM
MFBCRM_MCMC <- function(X, Y, W, p_rho, sigma, mtd, B) {
    .Call('_FBCRM_MFBCRM_MCMC', PACKAGE = 'FBCRM', X, Y, W, p_rho, sigma, mtd, B)
}

#'@importFrom Rcpp evalCpp
#'@useDynLib FBCRM
MFBCRM_RUNTRIAL <- function(cohort, max_samp, ptrue, W, p_rho, sigma, mtd, p_u, B, M, a, b, n) {
    .Call('_FBCRM_MFBCRM_RUNTRIAL', PACKAGE = 'FBCRM', cohort, max_samp, ptrue, W, p_rho, sigma, mtd, p_u, B, M, a, b, n)
}

